version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: nacky
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: postnest_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

